### PR TITLE
Update wci.py with changed URLs

### PR DESCRIPTION
**Pull request by EckhardM**
VW changed the URLs again

### CODE REVIEW

**Review by pola — APPROVED** [review]
It would be great if they could tell us in advance... :)

Super! Thank you!

**Comment by pola** [comment]
Can you merge this pull request on your own, or do I have to do it?

**Comment by EckhardM** [comment]
To be honest that was my first pull request so I am not familiar how to merge it into your repository :-)

**Comment by pola** [comment]
This is the first pull request from a fork that I recieve, but I'll go ahead and merge it now :)

**Pull request merged**
